- Demo/AppDelegate.swift
- Sources/Extensions/UIColor.swift
- Sources/Extensions/UIToolbar.swift
- Sources/Helper/Theme.swift
- Sources/Helper/ThemeManager.swift
Jira Task [HW-52048](https://jira.site1.hyperwallet.local/browse/HW-51681)
> HW-52048 Only White Theme Implementation

- Sources/TransferMethod/ListTransferMethodPresenter.swift
- Sources/TransferMethod/ListTransferMethodTableViewCell.swift
- Sources/TransferMethod/SelectTransferMethodTypeCell.swift
- UITests/TransferMethod/ListTransferMethodTests.swift
Jira task [HW-52654](https://jira.site1.hyperwallet.local/browse/HW-52654)
> HW-52654 PayPal Account Second Line

- Sources/TransferMethod/CountryCurrencyCell.swift
Jira task [HW-53249](https://jira.site1.hyperwallet.local/browse/HW-53249)
> HW-53249 country code is hidden for longer names

- Sources/Localization/en.lproj/Localizable.strings
- Sources/View/Widget/DateWidget.swift
- Sources/View/Widget/ExpiryDatePickerView.swift
Jira [HW-52982](https://jira.site1.hyperwallet.local/browse/HW-52982)
<p>
</p>
<p>
</p>
<p>
</p>
> HW-52982 Date pickers localization fix

- Sources/Receipt/ReceiptDetailTableViewCell.swift
- Sources/Receipt/ReceiptDetailTableViewController.swift
- Sources/Receipt/ReceiptFeeTableViewCell.swift
- Sources/Receipt/ReceiptNotesTableViewCell.swift
- UITests/Receipts/ListReceiptTests.swift
Jira [HW-53886](https://jira.site1.hyperwallet.local/browse/HW-53886)
> HW-53886 Missing accessibility id for transaction detail view

- Sources/Receipt/ReceiptDetailTableViewController.swift
> HW-52981 Fixed left inset on iOS 10.0 iPhone 5plus/6plus in landscape

- Sources/Receipt/ReceiptDetailTableViewController.swift
> HW-54045 Add inset separator in receipt details

- Sources/TransferMethod/ListTransferMethodPresenter.swift
Jira [HW-54347](https://jira.site1.hyperwallet.local/browse/HW-54347)
> HW-54347 Fix list transfer methods last four digits

- HyperwalletUISDK.xcodeproj/project.pbxproj
- Transfer/Sources/CreateTransferPresenter.swift
- Transfer/Tests/CreateTransferPresenterTests.swift
- Transfer/Tests/Helper/TransferMethodRepositoryRequestHelper.swift
- Transfer/Tests/Responses/UnexpectedErrorResponse.json
Added more tests to createTransferTests and added failure case for showSelectDestinationAccountView
> Added Tests to showSelectDestinationAccountView() Method

- .slather.yml
- Common/Sources/Extensions/UIView.swift
- Common/Sources/Localization/en.lproj/Localizable.strings
- Demo/IntegratorAuthenticationProvider.swift
- Demo/ViewController.swift
- HyperwalletUISDK.xcodeproj/project.pbxproj
- Transfer/Sources/CreateTransferController.swift
- Transfer/Sources/CreateTransferPresenter.swift
- Transfer/Sources/TransferAllFundsCell.swift
- Transfer/Sources/TransferAmountCell.swift
- Transfer/Sources/TransferButtonCell.swift
- Transfer/Sources/TransferDestinationCell.swift
- Transfer/Sources/TransferForeignExchangeCell.swift
- Transfer/Sources/TransferNotesCell.swift
- Transfer/Sources/View/TransferTableViewFooterView.swift
- Transfer/Tests/CreateTransferPresenterTests.swift
- Transfer/Tests/Helper/HyperwalletTestHelper.swift
- Transfer/Tests/Helper/TransferMethodRepositoryRequestHelper.swift
- Transfer/Tests/Helper/TransferRequestHelper.swift
- Transfer/Tests/Helper/UserRepositoryRequestHelper.swift
- Transfer/Tests/ScheduleTransferPresenterTests.swift
- UITests/Helper/TransferFunds/TransferFunds.swift
- UITests/TransferFunds/TransferUserFundsPPCTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
- fixed issue of showing the Transfer view when Transfer list is empty 
- Implemented the under-section assertions
> HW-55005-UI Error Handling (2)

- Common/Sources/Localization/en.lproj/Localizable.strings
- Transfer/Sources/CreateTransferPresenter.swift
- Transfer/Sources/CreateTransferSectionData.swift
- UITests/BaseTests/BaseTest.swift
- UITests/TransferFunds/TransferUserFundsPPCTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
Jira [HW-56157](https://jira.site1.hyperwallet.local/browse/HW-56157)
> HW-56157 Add currency to amount

- .swiftlint.yml
- .travis.yml
- Cartfile.private
- Receipt/Sources/ReceiptDetailSectionData.swift
- Sources/Receipt/ReceiptDetailSectionData.swift
- TransferMethod/Sources/SelectTransferMethodTypeController.swift
- UITests/BaseTests/BaseTest.swift
- UITests/Extensions/XCTestCase.swift
- UITests/Helper/HyperwalletMockWebServer.swift
- UITests/Helper/TransferFunds/TransferFunds.swift
- UITests/Helper/TransferFunds/TransferFundsConfirmation.swift
- UITests/Receipts/ListReceiptTests.swift
- UITests/Receipts/PrepaidCardListReceiptTests.swift
- UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
- UITests/TransferFunds/TransferUserFundsPPCTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
Jira [HW-57070](https://jira.site1.hyperwallet.local/browse/HW-57070)
> HW-57070 Fix flaky test in iOS UI SDK

- Cartfile.private
- Common/Sources/Insights/HyperwalletInsights.swift
- Common/Tests/Helper/HyperwalletInsightsMock.swift
- HyperwalletUISDK.xcodeproj/project.pbxproj
- TransferMethod/Sources/AddTransferMethodController.swift
- TransferMethod/Sources/AddTransferMethodPresenter.swift
- TransferMethod/Sources/View/Widget/AbstractWidget.swift
- TransferMethod/Sources/View/Widget/DateWidget.swift
- TransferMethod/Sources/View/Widget/NumberWidget.swift
- TransferMethod/Sources/View/Widget/PhoneWidget.swift
- TransferMethod/Sources/View/Widget/WidgetFactory.swift
- TransferMethod/Tests/AddTransferMethodPresenterTests.swift
- TransferMethod/Tests/Responses/HyperwalletFieldResponse.json
- TransferMethod/Tests/SelectTransferMethodTypePresenterTests.swift
- TransferMethod/Tests/View/Widget/AbstractWidgetTests.swift
Jira : https://jira.site1.hyperwallet.local/browse/HW-55477
> HW-55477 : US10 - Add Transfer Method - Send event when input error occurs

- Cartfile
- Common/Sources/Localization/en.lproj/Localizable.strings
HW-67510 : Update UI SDK localizable.strings
> HW-67510 : Update UI SDK localizable.strings

- Common/Sources/Extensions/UIViewController.swift
- Receipt/Sources/ListReceiptController.swift
- Transfer/Sources/CreateTransferController.swift
- TransferMethod/Sources/AddTransferMethodController.swift
- TransferMethod/Sources/ListTransferMethodController.swift
- TransferMethod/Sources/SelectTransferMethodTypeController.swift
- UITests/TransferMethod/AddTransferMethodBankAccountBusinessTests.swift
> Added AdaptivePresentationControllerDelegate for controllers.

- Transfer/Sources/View/TransferTableViewFooterView.swift
Adding Left margin for Confirmation Detail footer text for FX
> issue Fixed for footer text margin

- Demo/ViewController.swift
- TransferMethod/Sources/UpdateTransferMethodController.swift
- TransferMethod/Sources/UpdateTransferMethodSectionData.swift
- TransferMethod/Sources/View/Widget/SelectionWidget.swift
- TransferMethod/Tests/Responses/BankCardUpdateResponse.json
- TransferMethod/Tests/Responses/PayPalUpdateResponse.json
> Update Transfer Method UI Design

- Common/Sources/Localization/en.lproj/Localizable.strings
Localization file updated for content strings
> Localization file updated for content strings

- .swiftlint.yml
- .travis.yml
- Cartfile.private
- Common/Sources/Extensions/UIAlertAction.swift
- Common/Sources/Extensions/UIViewController.swift
- Common/Sources/HyperwalletUI.swift
- Common/Tests/Extensions/StringTests.swift
- Demo/ViewController.swift
- HyperwalletUISDK.xcodeproj/project.pbxproj
- Receipt/Tests/ListReceiptPresenterTests.swift
- Transfer/Tests/TransferAmountCurrencyFormatter.swift
- TransferMethod/Sources/AddTransferMethodController.swift
- TransferMethod/Sources/ListTransferMethodController.swift
- TransferMethod/Sources/UpdateTransferMethodController.swift
- TransferMethod/Sources/View/Widget/AbstractWidget.swift
- TransferMethod/Sources/View/Widget/DateWidget.swift
- TransferMethodRepository/Tests/TransferMethodConfigurationRepositoryTests.swift
- TransferMethodRepository/Tests/TransferMethodRepositoryTests.swift
- UITests/Extensions/XCUIElement.swift
- UITests/Helper/TransferMethod/SelectTransferMethodType.swift
- UITests/Receipts/ListAllReceiptsTests.swift
- UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
- UITests/TransferMethod/AddTransferMethodBankAccountIndividualTests.swift
- UITests/TransferMethod/AddTransferMethodBankCardTests.swift
- UITests/TransferMethod/ListTransferMethodTests.swift
- UITests/TransferMethod/UpdateTransferMethodBankAccountIndividualTests.swift
> Upgrading to Xcode 12

- Cartfile
- Transfer/Sources/CreateTransferPresenter.swift
- Transfer/Sources/ListTransferDestinationCell.swift
- Transfer/Sources/ListTransferSourceCell.swift
- Transfer/Sources/TransferDestinationCell.swift
- Transfer/Sources/TransferSourceCell.swift
- UITests/Helper/TransferFunds/TransferFunds.swift
- UITests/Helper/TransferFunds/TransferFundsConfirmation.swift
- UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
… tests.
Updated cartfile to used development branch of Insight SDK
> Updated prepaid card display.

- .travis.yml
Update Travis CI to run the test on Xcode 13
> DTSERWONE-821 - Support XCode 13 on Travis CI

- Cartfile
Minor change to update Hyperwallet SDK version
>  feature/DTSERWONE-821 Update SDK version

- .github/workflows/ci.yml
- Cartfile
- Cartfile.resolved
- Common/CurrencyFormatter.swift
- Common/Sources/Helper/HyperwalletIcon.swift
- Common/Sources/Helper/Theme.swift
- Common/Tests/Extensions/StringTests.swift
- Demo/ViewController.swift
- HyperwalletUISDK.podspec
- HyperwalletUISDK.xcodeproj/project.pbxproj
- Receipt/Tests/ListReceiptPresenterTests.swift
- Transfer/Sources/Coordinators/TransferCoordinators.swift
- Transfer/Sources/CreateTransferPresenter.swift
- TransferMethod/Sources/View/Widget/AbstractWidget.swift
- TransferMethod/Tests/View/Widget/TextWidgetTests.swift
- TransferMethodRepository/Tests/TransferMethodConfigurationRepositoryTests.swift
- UITests/Helper/TransferMethod/AddTransferMethod.swift
- UITests/Helper/TransferMethod/UpdateTransferMethod.swift
- UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
- UITests/TransferFunds/TransferUserFundsTest.swift
- fastlane/Fastfile
- Address swift lint issues
- Add support to build on Xcode 14.0
- Remove swift lint from build flow since CI will handle it
> DTSERWONE-821 Address swift lint v0.50 violations

- CHANGELOG.md
- Cartfile
- HyperwalletUISDK.podspec
- HyperwalletUISDK.xcodeproj/project.pbxproj
- PrivacyInfo.xcprivacy
Updated:
* Update version
* Add security context
> [DTSERWONE-1986] add security context and update version

- CHANGELOG.md
- Common/Sources/Generics/GenericController.swift
- Demo/IntegratorAuthenticationProvider.swift
- HyperwalletUISDK.podspec
- HyperwalletUISDK.xcodeproj/project.pbxproj
- README.md
- Receipt/Sources/ListReceiptController.swift
- Receipt/Sources/ReceiptDetailController.swift
- Transfer/Sources/CreateTransferController.swift
- Transfer/Sources/ListTransferDestinationController.swift
- Transfer/Sources/ListTransferSourceController.swift
- Transfer/Sources/ScheduleTransferController.swift
- TransferMethod/Sources/AddTransferMethodController.swift
- TransferMethod/Sources/ListTransferMethodController.swift
- TransferMethod/Sources/SelectTransferMethodTypeController.swift
- TransferMethod/Sources/UpdateTransferMethodController.swift
On iOS 18 when mobile is not use navigation bar the UI SDK is not displayed the `back` and `action button`
- Enable navigation when disabled 
- Bump up version to 1.0.2
https://github.com/user-attachments/assets/75ac9633-c656-4e71-ba0a-f518b578038f
> DTPOMERSER-1411  - FIx iOS 18  hidden navigation bar
